import {test} from 'node:test';
import assert from 'node:assert/strict';
process.env.NODE_ENV='test';
const {candidates}=await import('../server.mjs');
test('candidate counts deduplicate authors per paper and retain source evidence',()=>{const author={name:'Jane Smith',short:'Smith J',affiliations:[],orcid:null};const result=candidates([{id:'1',title:'Study one',url:'https://example.org/1',citations:5,authors:[author,author]},{id:'2',title:'Study two',url:'https://example.org/2',citations:2,authors:[{...author,affiliations:['Verified in paper']}]}]);assert.equal(result.length,1);assert.equal(result[0].count,2);assert.equal(result[0].citations,7);assert.equal(result[0].papers.length,2);assert.deepEqual(result[0].affiliations,['Verified in paper']);});
test('discovery sorts by sampled appearances before paper citations',()=>{const a={name:'A',short:'A',affiliations:[]},b={name:'B',short:'B',affiliations:[]};const r=candidates([{id:'1',citations:100,authors:[a,b]},{id:'2',citations:0,authors:[b]}]);assert.equal(r[0].name,'B');});

test('publication normalization skips unnamed source authors and missing affiliation values',async()=>{const {paper}=await import('../server.mjs');const normalized=paper({id:'123',source:'MED',authorList:{author:[{firstName:'Jedd D',lastName:'Wolchok',fullName:'Wolchok JD',authorAffiliationDetailsList:{authorAffiliation:[{},null,{affiliation:'Weill Cornell Medicine'}]}},{authorAffiliationDetailsList:{authorAffiliation:[]}},{fullName:'Named Consortium'}]}});assert.equal(normalized.authors.length,2);assert.equal(normalized.authors[0].name,'Jedd D Wolchok');assert.deepEqual(normalized.authors[0].affiliations,['Weill Cornell Medicine']);assert.equal(normalized.authors[1].name,'Named Consortium');});

test('browser collaboration processing tolerates incomplete author records',async()=>{const {readFile}=await import('node:fs/promises');const vm=await import('node:vm');const source=await readFile(new URL('../public/app.js',import.meta.url),'utf8');const start=source.indexOf('function knownInstitution('),end=source.indexOf('function mapNodes(');const ctx=vm.createContext({data:{name:'Jedd Wolchok',literature:{papers:[{id:'1',authors:[{name:'Jedd D Wolchok',affiliations:[]},{affiliations:[]},{name:'Named Collaborator',affiliations:[undefined,'Weill Cornell Medicine']}]}]}}});vm.runInContext(source.slice(start,end),ctx);assert.equal(vm.runInContext('matchingAuthor({})',ctx),false);assert.equal(vm.runInContext('knownInstitution(undefined)',ctx),null);assert.equal(vm.runInContext('collaborators().length',ctx),1);assert.equal(vm.runInContext('collaborators()[0].name',ctx),'Named Collaborator');});
