import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {generateKeyPairSync,sign} from 'node:crypto';
import {Keypair,PublicKey,TransactionMessage,TransactionInstruction,VersionedTransaction,SystemProgram} from '@solana/web3.js';
process.env.NODE_ENV='test';process.env.STORAGE_PATH=await mkdtemp(tmpdir()+'/exchange-test-');
const {server,validateCard,decode58,checkTransaction}=await import('../server.mjs');
const data={name:'The Ghost',ticker:'GHOST',category:'Ghosted',duration:'Six weeks',story:'Went out for oat milk. Never returned.',goal:'One very quiet vacation',target:3,avatar:1,anonymous:true};
function encode(bytes){const chars='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(const b of bytes)n=n*256n+BigInt(b);let s='';while(n){s=chars[Number(n%58n)]+s;n/=58n;}for(const b of bytes){if(b)break;s='1'+s;}return s;}
function identity(){const keys=generateKeyPairSync('ed25519');return {...keys,wallet:encode(keys.publicKey.export({type:'spki',format:'der'}).subarray(-32))};}
const originFetch=globalThis.fetch;let rpcState='pending',preparedBytes;
function creation(wallet,mint,card,uri,creator=wallet,transfer=false){const str=s=>{const b=Buffer.from(s),n=Buffer.alloc(4);n.writeUInt32LE(b.length);return Buffer.concat([n,b]);};const ix=new TransactionInstruction({programId:new PublicKey('6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'),keys:[{pubkey:new PublicKey(mint),isSigner:true,isWritable:true},{pubkey:new PublicKey(wallet),isSigner:true,isWritable:true}],data:Buffer.concat([Buffer.from([214,144,76,236,95,139,49,180]),str(card.name),str(card.ticker),str(uri),decode58(creator),Buffer.alloc(11)])});const instructions=[ix];if(transfer)instructions.push(SystemProgram.transfer({fromPubkey:new PublicKey(wallet),toPubkey:Keypair.generate().publicKey,lamports:1}));return new VersionedTransaction(new TransactionMessage({payerKey:new PublicKey(wallet),recentBlockhash:Keypair.generate().publicKey.toBase58(),instructions}).compileToV0Message()).serialize();}
globalThis.fetch=async(url,options)=>{if(url==='https://pumpportal.fun/api/trade-local'){const args=JSON.parse(options.body);preparedBytes=creation(args.publicKey,args.mint,{name:args.tokenMetadata.name,ticker:args.tokenMetadata.symbol},args.tokenMetadata.uri);return new Response(preparedBytes);}if(url==='https://api.mainnet-beta.solana.com')return Response.json({result:rpcState==='pending'?null:{meta:{err:rpcState==='failed'?{InstructionError:[0,'error']}:null},transaction:[Buffer.from(preparedBytes).toString('base64'),'base64']}});return originFetch(url,options);};
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
async function call(path,body,cookie=''){const r=await originFetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Cookie:cookie},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function login(who){const c=await call('/api/challenge',{wallet:who.wallet});return call('/api/auth',{id:c.data.id,signature:encode(sign(null,Buffer.from(c.data.message),who.privateKey))});}
test('anonymous card validation rejects identifiers, malformed values, and unconfirmed identity',()=>{assert.equal(validateCard(data).ticker,'GHOST');for(const patch of [{story:'Contact me @realperson'},{story:'Phone 555-123-4567'},{ticker:'BAD NAME'},{avatar:NaN},{target:Infinity},{anonymous:false}])assert.throws(()=>validateCard({...data,...patch}));});
test('launch transaction validation rejects mismatched creator, metadata and direct transfers',()=>{const wallet=Keypair.generate().publicKey.toBase58(),mint=Keypair.generate().publicKey.toBase58(),uri='https://example.test/meta.json';const tx=creation(wallet,mint,data,uri);assert.equal(checkTransaction(tx,wallet,mint,data,uri).length,64);assert.throws(()=>checkTransaction(tx,wallet,mint,{...data,ticker:'OTHER'},uri));assert.throws(()=>checkTransaction(creation(wallet,mint,data,uri,Keypair.generate().publicKey.toBase58()),wallet,mint,data,uri));assert.throws(()=>checkTransaction(creation(wallet,mint,data,uri,wallet,true),wallet,mint,data,uri));});
test('signed publishing, authorization, deduplicated reactions and verified launch lifecycle',async()=>{const who=identity(),other=identity();assert.equal((await call('/api/cards',data)).status,400);const challenge=await call('/api/challenge',{wallet:who.wallet});const forged=await call('/api/auth',{id:challenge.data.id,signature:encode(sign(null,Buffer.from(challenge.data.message),other.privateKey))});assert.equal(forged.status,401);const signed=encode(sign(null,Buffer.from(challenge.data.message),who.privateKey));const auth=await call('/api/auth',{id:challenge.data.id,signature:signed});assert.equal(auth.status,200);assert.equal((await call('/api/auth',{id:challenge.data.id,signature:signed})).status,400);const cookie=auth.cookie;const card=await call('/api/cards',data,cookie);assert.equal(card.status,201);assert.equal(card.data.status,'story');const reaction=await call('/api/react',{id:card.data.id,reaction:'flag'});const reacted=await call('/api/react',{id:card.data.id,reaction:'escape'},reaction.cookie);assert.deepEqual(reacted.data.reactions,{escape:1});const otherAuth=await login(other);assert.equal((await call(`/api/cards/${card.data.id}/update`,{text:'Not my story'},otherAuth.cookie)).status,400);assert.equal((await call(`/api/cards/${card.data.id}/update`,{text:'Bought a better hoodie.'},cookie)).data.updates.length,1);assert.equal((await call('/api/report',{id:card.data.id,reason:'Identifying information'})).status,200);const launch=await call('/api/launch/prepare',{...data,mint:Keypair.generate().publicKey.toBase58(),amount:0,image:'data:image/png;base64,'+Buffer.from([137,80,78,71,13,10,26,10]).toString('base64')},cookie);assert.equal(launch.status,200);let list=await call('/api/cards');assert.equal(list.data.cards.length,1);const pending={id:launch.data.id,signature:'1'.repeat(64)};assert.equal((await call('/api/launch/confirm',pending,cookie)).status,202);rpcState='failed';assert.equal((await call('/api/launch/confirm',pending,cookie)).status,400);assert.equal((await call('/api/cards')).data.cards.length,1);rpcState='confirmed';const live=await call('/api/launch/confirm',pending,cookie);assert.equal(live.data.status,'live');assert.equal((await call('/api/cards')).data.cards.length,2);});
test.after(()=>{globalThis.fetch=originFetch;server.close();});
