import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID,randomBytes,createPublicKey,verify,createHash} from 'node:crypto';
import {VersionedTransaction,AddressLookupTableAccount,PublicKey} from '@solana/web3.js';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('./public/',import.meta.url));
const directory=process.env.STORAGE_PATH||process.env.RAILWAY_VOLUME_MOUNT_PATH||fileURLToPath(new URL('./data/',import.meta.url));
await mkdir(directory,{recursive:true});
const db=new DatabaseSync(`${directory}/exchange.sqlite`);db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS stories(id TEXT PRIMARY KEY,data TEXT NOT NULL,wallet TEXT NOT NULL,status TEXT NOT NULL,image BLOB,metadata TEXT,message_hash TEXT); CREATE TABLE IF NOT EXISTS challenges(id TEXT PRIMARY KEY,wallet TEXT,message TEXT,expires INTEGER); CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,wallet TEXT,expires INTEGER); CREATE TABLE IF NOT EXISTS reactions(story TEXT,visitor TEXT,reaction TEXT,PRIMARY KEY(story,visitor)); CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY,story TEXT,reason TEXT,created TEXT);`);
export const categories=['Ghosted','Cheated','Situationship','Still texting','Dodged a bullet'];
const alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
export function decode58(s){if(typeof s!=='string'||s.length>100)throw Error('Invalid wallet or signature.');let n=0n;for(const c of s){const i=alphabet.indexOf(c);if(i<0)throw Error('Invalid wallet or signature.');n=n*58n+BigInt(i);}let h=n.toString(16);if(h.length%2)h='0'+h;return Buffer.concat([Buffer.alloc(s.match(/^1*/)[0].length),n?Buffer.from(h,'hex'):Buffer.alloc(0)]);}
function key(s){if(decode58(s).length!==32)throw Error('Choose a valid Solana wallet.');return s;}
export function validateCard(x){const text=(v,max,label)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw Error(`Check your ${label}.`);if(/https?:|www\.|@|\b\d[\d ()+.-]{7,}\d\b/i.test(v))throw Error('Keep stories anonymous: no links, handles or contact details.');return v.trim();};const card={name:text(x.name,32,'fictional nickname'),ticker:text(x.ticker,10,'ticker').toUpperCase(),story:text(x.story,500,'final straw'),duration:text(x.duration,40,'relationship length'),goal:text(x.goal,90,'fresh start goal'),category:x.category,avatar:Number(x.avatar),target:Number(x.target)};if(!/^[A-Z][A-Z0-9]{1,9}$/.test(card.ticker))throw Error('Use 2–10 letters or numbers for your ticker.');if(!categories.includes(card.category)||!Number.isInteger(card.avatar)||card.avatar<0||card.avatar>5||!Number.isFinite(card.target)||card.target<0.1||card.target>10000)throw Error('Check your category, artwork and SOL goal.');if(x.anonymous!==true)throw Error('Confirm your story uses a fictional persona.');return card;}
const json=(res,data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>800000)throw Error('Upload is too large.');}try{return JSON.parse(s);}catch{throw Error('Invalid request.');}}
const rates=new Map();function limit(req){const ip=req.headers['x-forwarded-for']?.split(',')[0]||req.socket.remoteAddress;const now=Date.now();const r=rates.get(ip)||{n:0,t:now};if(now-r.t>60000){r.n=0;r.t=now;}if(++r.n>60)throw Error('Take a breath. Try again in a minute.');rates.set(ip,r);if(rates.size>5000)rates.clear();}
function cookie(req,name){return req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1);}
function session(req){const row=db.prepare('SELECT wallet FROM sessions WHERE id=? AND expires>?').get(cookie(req,'session')||'',Date.now());if(!row)throw Error('Connect your wallet and sign in first.');return row.wallet;}
function getStory(id){const row=db.prepare('SELECT * FROM stories WHERE id=?').get(id);if(!row)throw Error('Card not found.');return row;}
function publicCard(row){const data=JSON.parse(row.data);const reactions=Object.fromEntries(db.prepare('SELECT reaction,count(*) n FROM reactions WHERE story=? GROUP BY reaction').all(row.id).map(x=>[x.reaction,x.n]));return {...data,id:row.id,status:row.status,wallet:row.wallet,reactions};}
const PUMP='6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P';
export function checkTransaction(bytes,wallet,mint,card,uri,lookupAccounts=[]){const tx=VersionedTransaction.deserialize(bytes);const m=tx.message;const resolved=m.getAccountKeys({addressLookupTableAccounts:lookupAccounts});const keys=Array.from({length:resolved.length},(_,i)=>resolved.get(i).toBase58());if(keys[0]!==wallet||m.header.numRequiredSignatures!==2||!keys.slice(0,2).includes(mint))throw Error('Launch signer mismatch.');const create=m.compiledInstructions.find(i=>keys[i.programIdIndex]===PUMP&&(Buffer.from(i.data).subarray(0,8).equals(Buffer.from([24,30,200,40,5,28,7,119]))||Buffer.from(i.data).subarray(0,8).equals(Buffer.from([214,144,76,236,95,139,49,180]))));if(!create||keys[create.accountKeyIndexes[0]]!==mint)throw Error('Missing token creation instruction.');const b=Buffer.from(create.data);let offset=8;for(const expected of [card.name,card.ticker,uri]){const n=b.readUInt32LE(offset);offset+=4;if(b.subarray(offset,offset+n).toString()!==expected)throw Error('Token metadata mismatch.');offset+=n;}if(!b.subarray(offset,offset+32).equals(decode58(wallet)))throw Error('Creator wallet mismatch.');offset+=32;if(b[0]===214&&(b[offset]!==0||b[offset+1]===1||(b.length>offset+10&&b[offset+10]===1)))throw Error('This launch must use standard creator fees.');for(const i of m.compiledInstructions){if(keys[i.programIdIndex]==='11111111111111111111111111111111'&&Buffer.from(i.data).readUInt32LE(0)===2)throw Error('Unexpected wallet transfer.');}return createHash('sha256').update(m.serialize()).digest('hex');}
async function upstream(url,options={}){const r=await fetch(url,{...options,signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error(`Launch provider unavailable (${r.status}). No transaction was submitted.`);return r;}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://local');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');if(u.pathname==='/health')return json(res,{ok:true,app:'EXCHANGE'});if(req.method==='POST'){limit(req);const origin=req.headers.origin;const expected=process.env.PUBLIC_URL||`https://${req.headers.host}`;if(origin&&origin!==expected&&!(process.env.NODE_ENV!=='production'&&origin===`http://${req.headers.host}`))return json(res,{error:'Request origin rejected.'},403);}
if(u.pathname==='/api/cards'&&req.method==='GET')return json(res,{cards:db.prepare("SELECT * FROM stories WHERE status IN ('story','live') ORDER BY rowid DESC LIMIT 200").all().map(publicCard)});
if(u.pathname==='/api/me'){let wallet=null;try{wallet=session(req);}catch{}return json(res,{wallet});}
if(u.pathname==='/api/challenge'&&req.method==='POST'){const x=await body(req);const wallet=key(x.wallet);const id=randomUUID();const message=`EXCHANGE wallet sign-in\nWallet: ${wallet}\nNonce: ${id}\nThis signature authorizes story management only. No funds are moved.\nExpires: ${new Date(Date.now()+300000).toISOString()}`;db.prepare('INSERT INTO challenges VALUES(?,?,?,?)').run(id,wallet,message,Date.now()+300000);return json(res,{id,message});}
if(u.pathname==='/api/auth'&&req.method==='POST'){const x=await body(req);const c=db.prepare('SELECT * FROM challenges WHERE id=? AND expires>?').get(x.id,Date.now());if(!c)throw Error('Sign-in expired. Try again.');const publicKey=createPublicKey({key:Buffer.concat([Buffer.from('302a300506032b6570032100','hex'),decode58(c.wallet)]),format:'der',type:'spki'});if(!verify(null,Buffer.from(c.message),publicKey,decode58(x.signature)))return json(res,{error:'Wallet signature rejected.'},401);db.prepare('DELETE FROM challenges WHERE id=?').run(x.id);const id=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(id,c.wallet,Date.now()+3600000);res.setHeader('Set-Cookie',`session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=3600${process.env.NODE_ENV==='production'?'; Secure':''}`);return json(res,{wallet:c.wallet});}
if(u.pathname==='/api/logout'&&req.method==='POST'){db.prepare('DELETE FROM sessions WHERE id=?').run(cookie(req,'session')||'');res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,{ok:true});}
if(u.pathname==='/api/cards'&&req.method==='POST'){const wallet=session(req),x=await body(req),card=validateCard(x),id=randomUUID();card.created=new Date().toISOString();card.updates=[];db.prepare('INSERT INTO stories(id,data,wallet,status) VALUES(?,?,?,?)').run(id,JSON.stringify(card),wallet,'story');return json(res,publicCard(getStory(id)),201);}
if(u.pathname==='/api/launch/prepare'&&req.method==='POST'){const wallet=session(req),x=await body(req),card=validateCard(x),mint=key(x.mint);const amount=Number(x.amount);if(!Number.isFinite(amount)||amount<0||amount>10)throw Error('First buy must be between 0 and 10 SOL.');const image=Buffer.from(String(x.image||'').replace(/^data:image\/png;base64,/,''),'base64');if(image.length>500000||!image.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))throw Error('Choose generated card artwork.');const id=randomUUID(),origin=process.env.PUBLIC_URL||`https://${req.headers.host}`,uri=`${origin}/metadata/${id}.json`;card.created=new Date().toISOString();card.mint=mint;card.updates=[];const metadata={name:card.name,symbol:card.ticker,description:`${card.story}\nFresh start goal: ${card.goal}. Fictional anonymous breakup persona.`,image:`${origin}/art/${id}.png`,external_url:`${origin}/?card=${id}`,website:`${origin}/?card=${id}`,showName:true};db.prepare('INSERT INTO stories(id,data,wallet,status,image,metadata) VALUES(?,?,?,?,?,?)').run(id,JSON.stringify(card),wallet,'pending',image,JSON.stringify(metadata));const r=await upstream('https://pumpportal.fun/api/trade-local',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({publicKey:wallet,action:'create',tokenMetadata:{name:card.name,symbol:card.ticker,uri},mint,denominatedInSol:'true',amount,slippage:10,priorityFee:0.00005,pool:'pump',isMayhemMode:false,isCashbackEnabled:false,isHolderReward:false})});const bytes=Buffer.from(await r.arrayBuffer());const lookups=VersionedTransaction.deserialize(bytes).message.addressTableLookups||[];let lookupAccounts=[];if(lookups.length){const rpc=await upstream(process.env.SOLANA_RPC_URL||'https://api.mainnet-beta.solana.com',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'getMultipleAccounts',params:[lookups.map(l=>l.accountKey.toBase58()),{encoding:'base64',commitment:'confirmed'}]})});const result=await rpc.json();lookupAccounts=lookups.map((l,i)=>{const a=result.result?.value?.[i];if(!a||a.owner!=='AddressLookupTab1e1111111111111111111111111')throw Error('Unable to verify launch lookup table. Try again.');return new AddressLookupTableAccount({key:l.accountKey,state:AddressLookupTableAccount.deserialize(Buffer.from(a.data[0],'base64'))});});}const hash=checkTransaction(bytes,wallet,mint,card,uri,lookupAccounts);db.prepare('UPDATE stories SET message_hash=? WHERE id=?').run(hash,id);return json(res,{id,transaction:bytes.toString('base64'),mint});}
if(u.pathname==='/api/launch/confirm'&&req.method==='POST'){const wallet=session(req),x=await body(req),row=getStory(x.id);if(row.wallet!==wallet||!row.message_hash)throw Error('Launch does not belong to this wallet.');if(decode58(x.signature).length!==64)throw Error('Invalid transaction signature.');const rpc=await upstream(process.env.SOLANA_RPC_URL||'https://api.mainnet-beta.solana.com',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'getTransaction',params:[x.signature,{encoding:'base64',commitment:'confirmed',maxSupportedTransactionVersion:0}]})});const data=await rpc.json();if(!data.result)return json(res,{pending:true,message:'Waiting for Solana confirmation. Keep this page open.'},202);if(data.result.meta?.err)throw Error('The launch transaction failed. Your card has not been listed.');const tx=VersionedTransaction.deserialize(Buffer.from(data.result.transaction[0],'base64'));const hash=createHash('sha256').update(tx.message.serialize()).digest('hex');if(hash!==row.message_hash)throw Error('Transaction does not match this launch.');const card=JSON.parse(row.data);card.signature=x.signature;db.prepare("UPDATE stories SET status='live',data=? WHERE id=?").run(JSON.stringify(card),row.id);return json(res,publicCard(getStory(row.id)));}
if(/^\/api\/cards\/[^/]+\/update$/.test(u.pathname)&&req.method==='POST'){const wallet=session(req),id=u.pathname.split('/')[3],row=getStory(id),x=await body(req);if(row.wallet!==wallet)throw Error('Only the creator can update this card.');const card=JSON.parse(row.data),text=String(x.text||'').trim();if(text.length<3||text.length>300||/https?:|www\.|@|\b\d[\d ()+.-]{7,}\d\b/i.test(text))throw Error('Use 3–300 characters without identifying details.');card.updates=[{text,date:new Date().toISOString()},...(card.updates||[])].slice(0,20);db.prepare('UPDATE stories SET data=? WHERE id=?').run(JSON.stringify(card),id);return json(res,publicCard(getStory(id)));}
if(u.pathname==='/api/react'&&req.method==='POST'){const x=await body(req),row=getStory(x.id);if(!['story','live'].includes(row.status)||!['flag','cooked','escape'].includes(x.reaction))throw Error('Choose an available card and reaction.');let visitor=cookie(req,'visitor');if(!/^[a-f0-9]{48}$/.test(visitor||'')){visitor=randomBytes(24).toString('hex');res.setHeader('Set-Cookie',`visitor=${visitor}; HttpOnly; SameSite=Strict; Path=/; Max-Age=31536000${process.env.NODE_ENV==='production'?'; Secure':''}`);}db.prepare('INSERT INTO reactions VALUES(?,?,?) ON CONFLICT(story,visitor) DO UPDATE SET reaction=excluded.reaction').run(x.id,visitor,x.reaction);return json(res,publicCard(getStory(x.id)));}
if(u.pathname==='/api/report'&&req.method==='POST'){const x=await body(req);getStory(x.id);if(!['Identifying information','Harassment','Other'].includes(x.reason))throw Error('Choose a report reason.');db.prepare('INSERT INTO reports VALUES(?,?,?,?)').run(randomUUID(),x.id,x.reason,new Date().toISOString());return json(res,{ok:true});}
const meta=u.pathname.match(/^\/(metadata|art)\/([a-f0-9-]{36})\.(json|png)$/);if(meta){const row=getStory(meta[2]);if(!row.metadata||!row.image)return json(res,{error:'Artwork not found.'},404);res.writeHead(200,{'Content-Type':meta[1]==='art'?'image/png':'application/json','Cache-Control':'public,max-age=31536000,immutable'});res.end(meta[1]==='art'?row.image:row.metadata);return;}
if(u.pathname.startsWith('/api/'))return json(res,{error:'Not found.'},404);
const path=u.pathname==='/'?'index.html':u.pathname.slice(1);if(!['index.html','app.js','style.css','art.js','wallet.js'].includes(path))return json(res,{error:'Not found.'},404);res.setHeader('Content-Type',path.endsWith('.html')?'text/html; charset=utf-8':path.endsWith('.css')?'text/css':'text/javascript');res.setHeader('Cache-Control','no-cache');res.end(await readFile(root+path));
}catch(e){console.error(e.message);json(res,{error:e.message||'Please try again.'},400);}});
if(process.env.NODE_ENV!=='test')server.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log(`EXCHANGE listening on ${server.address().port}`));
export {server};
