import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('./public/',import.meta.url));
const areas={Melanoma:'melanoma','Lung cancer':'"non-small cell lung cancer"','Colorectal cancer':'"colorectal cancer"',Ophthalmology:'(retina OR macular degeneration)',Immunology:'(rheumatoid arthritis OR autoimmune)',Cardiology:'(heart failure OR cardiovascular)',Neurology:'(Alzheimer OR Parkinson)',Dermatology:'(psoriasis OR atopic dermatitis)'};
const cache=new Map();
async function remote(url){const key=url.toString();if(cache.has(key)&&Date.now()-cache.get(key).time<900000)return cache.get(key).value;const res=await fetch(url,{signal:AbortSignal.timeout(25000),headers:{Accept:'application/json'}});if(!res.ok)throw new Error(`Source returned ${res.status}`);const value=await res.json();cache.set(key,{time:Date.now(),value});if(cache.size>150)cache.delete(cache.keys().next().value);return value;}
function clean(v){return String(v||'').replace(/[^\p{L}\p{N}\s.'-]/gu,'').trim().slice(0,100);}
function affiliations(a){return (a.authorAffiliationDetailsList?.authorAffiliation||[]).map(x=>x?.affiliation).filter(x=>typeof x==='string'&&x.trim());}
export function paper(r){return {id:r.id,title:r.title,date:r.firstPublicationDate||r.pubYear,journal:r.journalInfo?.journal?.title||'',citations:Number(r.citedByCount||0),url:`https://europepmc.org/article/${r.source}/${r.id}`,abstract:(r.abstractText||'').replace(/<[^>]+>/g,' '),authors:(r.authorList?.author||[]).map(a=>({name:[a.firstName,a.lastName].filter(Boolean).join(' ')||a.fullName,short:a.fullName||'',affiliations:affiliations(a),orcid:a.authorId?.type==='ORCID'?a.authorId.value:null})).filter(a=>typeof a.name==='string'&&a.name.trim())};}
async function literature(area,name,initials,years){const u=new URL('https://www.ebi.ac.uk/europepmc/webservices/rest/search');const parts=clean(name).split(/\s+/);const author=initials?`${parts.at(-1)} ${clean(initials)}`:`${parts.at(-1)} ${parts[0]?.[0]||''}`;const since=new Date();since.setFullYear(since.getFullYear()-years);const query= `TITLE_ABS:(${areas[area]}) AND SRC:MED AND FIRST_PDATE:[${since.toISOString().slice(0,10)} TO ${new Date().toISOString().slice(0,10)}]${name?` AND AUTHOR:"${author}"`:''}`;u.search=new URLSearchParams({query,format:'json',resultType:'core',pageSize:name?'50':'100',sort:'FIRST_PDATE_D desc'});const d=await remote(u);return {total:d.hitCount||0,papers:(d.resultList?.result||[]).map(paper),query,url:`https://europepmc.org/search?query=${encodeURIComponent(query)}`};}
async function trials(area,name){const u=new URL('https://clinicaltrials.gov/api/v2/studies');u.search=new URLSearchParams({'query.cond':({'Lung cancer':'non-small cell lung cancer',Ophthalmology:'macular degeneration OR retinal disease',Immunology:'rheumatoid arthritis OR autoimmune disease',Cardiology:'heart failure OR cardiovascular disease',Neurology:'Alzheimer disease OR Parkinson disease',Dermatology:'psoriasis OR atopic dermatitis'})[area]||area,'query.term':clean(name),pageSize:'10',format:'json',countTotal:'true',sort:'LastUpdatePostDate:desc'});const d=await remote(u);return {total:d.totalCount||0,studies:(d.studies||[]).map(s=>{const p=s.protocolSection;return {id:p.identificationModule.nctId,title:p.identificationModule.briefTitle,status:p.statusModule.overallStatus,phase:p.designModule?.phases?.join(', ')||'Not reported',sponsor:p.sponsorCollaboratorsModule?.leadSponsor?.name,updated:p.statusModule.lastUpdatePostDateStruct?.date,url:`https://clinicaltrials.gov/study/${p.identificationModule.nctId}`};})};}
export function candidates(papers){const map=new Map();for(const p of papers){const seen=new Set();for(const a of p.authors){if(!a.name||seen.has(a.name)||!a.short)continue;seen.add(a.name);const c=map.get(a.name)||{...a,count:0,citations:0,papers:[]};c.count++;c.citations+=p.citations;c.papers.push({id:p.id,title:p.title,url:p.url});if(!c.affiliations.length)c.affiliations=a.affiliations;map.set(a.name,c);}}return [...map.values()].sort((a,b)=>b.count-a.count||b.citations-a.citations).slice(0,25);}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://local');res.setHeader('X-Content-Type-Options','nosniff');if(u.pathname==='/health'){res.end('ok');return;}if(u.pathname.startsWith('/api/')){res.setHeader('Content-Type','application/json');const area=u.searchParams.get('area')||'Melanoma';if(!areas[area]){res.writeHead(400);res.end(JSON.stringify({error:'Choose a supported therapeutic area.'}));return;}const name=clean(u.searchParams.get('name'));const years=Math.max(1,Math.min(10,Number(u.searchParams.get('years'))||5));if(u.pathname==='/api/research'){const results=await Promise.allSettled([literature(area,name,u.searchParams.get('initials'),years),trials(area,name)]);const lit=results[0].status==='fulfilled'?results[0].value:null;res.end(JSON.stringify({area,name,years,retrieved:new Date().toISOString(),literature:lit,trials:results[1].status==='fulfilled'?results[1].value:null,candidates:lit?candidates(lit.papers):[],errors:results.map((r,i)=>r.status==='rejected'?`${i===0?'Europe PMC':'ClinicalTrials.gov'} unavailable: ${r.reason.message}`:null).filter(Boolean)}));return;}res.writeHead(404);res.end('{}');return;}const path=u.pathname==='/'?'index.html':u.pathname.slice(1);if(!['index.html','app.js','style.css','directory.json','map.json'].includes(path)){res.writeHead(404);res.end('Not found');return;}const content=await readFile(root+path);res.setHeader('Content-Type',({'html':'text/html','js':'text/javascript','css':'text/css','json':'application/json'})[path.split('.').at(-1)]);res.end(content);}catch(e){res.writeHead(500,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'Unable to complete research. Please try again.'}));}});
if(process.env.NODE_ENV!=='test')server.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log(`KOL Finder listening on 0.0.0.0:${server.address().port}`));
